version: '3.8'

services:
    backend:
        container_name: block-explorer
        build:
            context: .
        ports:
            - "8000:3000"
        volumes:
            - .:/app
            - /app/node_modules
